config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  root to: 'flights#index'
  resources :airports, only: :index
  
  resources :flights, only: :index
  resources :bookings
end

app/models/airport.rb
class Airport < ApplicationRecord
  has_many :departing_flights, class_name: 'Flight', foreign_key: 'departure_id', inverse_of: :departure_airport
  has_many :arriving_flights, class_name: 'Flight', foreign_key: 'arrival_id', inverse_of: :arrival_airport
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :flight
  has_many :passengers, dependent: :destroy
  accepts_nested_attributes_for :passengers, allow_destroy: true
end

app/models/flight.rb
class Flight < ApplicationRecord
  has_many :bookings
  has_many :passengers, through: :bookings
  belongs_to :departure_airport, class_name: 'Airport', foreign_key: :departure_id, inverse_of: :departing_flights
  belongs_to :arrival_airport, class_name: 'Airport', foreign_key: :arrival_id, inverse_of: :arriving_flights
end

app/models/passenger.rb
class Passenger < ApplicationRecord
  # has_many :bookings
  # has_many :flights, through: :bookings
  belongs_to :booking
  has_many :flights, through: :booking
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookings_controller.rb
# Scaffolded resource
class BookingsController < ApplicationController
  before_action :set_booking, only: %i[ show edit update destroy ]

  # GET /bookings or /bookings.json
  def index
    @bookings = Booking.all
  end

  # GET /bookings/1 or /bookings/1.json
  def show
  end

  # GET /bookings/new
  def new
    @booking = Booking.new
    @selected_flight = Flight.find(params[:flight_id])
    @passengers_count = params[:num_of_passengers].to_i
    # instantiating (not saving) already-associated-objects (X passengers with the booking)
    # @passengers_count.times { @booking.passengers.build }
  end

  # GET /bookings/1/edit
  def edit
  end

  # POST /bookings or /bookings.json
  def create
    @booking = Booking.new(booking_params)

    respond_to do |format|
      if @booking.save

        # The PassengerMailer sends confirmation email after booking saved
        PassengerMailer.with(booking: @booking).confirmation_email.deliver_now

        format.html { redirect_to booking_url(@booking), notice: "Booking was successfully created." }
        format.json { render :show, status: :created, location: @booking }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @booking.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bookings/1 or /bookings/1.json
  def update
    respond_to do |format|
      if @booking.update(booking_params)
        format.html { redirect_to booking_url(@booking), notice: "Booking was successfully updated." }
        format.json { render :show, status: :ok, location: @booking }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @booking.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bookings/1 or /bookings/1.json
  def destroy
    @booking.destroy

    respond_to do |format|
      format.html { redirect_to bookings_url, notice: "Booking was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_booking
      @booking = Booking.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def booking_params
      # params.fetch(:booking, {})
      params.require(:booking).permit(:flight_id, passengers_attributes: [:name, :email])
    end
end

app/controllers/flights_controller.rb
class FlightsController < ApplicationController

  def index
    @airports = Airport.all
    @flights = Flight.all
    @num_of_passengers = params[:passengers_num]
    # @searched_flights_testa = Flight.user_search(query_params)
    @searched_flights = Flight.where(departure_id: params[:departure_id],
    arrival_id: params[:arrival_id], start_date: params[:start_date])
  end

  private

    # Only allow a list of trusted parameters through.
    # I don't think this is being used, why not? Do I need to call `query_params` above?
    def query_params
      params.permit(:departure_id, :arrival_id, :start_date, :start_time, :passengers_num, :commit)
      puts "query_params method ran"
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/views/bookings/_booking.html.erb
<div id="<%= dom_id booking %>" class="booking-form">
  <p>
    Flight ID: <%= booking.flight_id %>
  </p>

  <% booking.passengers.each_with_index do |passenger, idx| %>
    <p> Passenger #<%= idx +1 %></p>
    <ul>
      <li> Name: <%= passenger.name %></li>
      <li> Email: <%= passenger.email %></li>
    </ul>
  <% end %>

</div>

app/views/bookings/_booking.text.erb
Flight ID: <%= booking.flight_id %>

 <% booking.passengers.each_with_index do |passenger, idx| %>
    Passenger #<%= idx +1 %>
    
    Name: <%= passenger.name %>
    Email: <%= passenger.email %>
  <% end %>

app/views/bookings/_form.html.erb
<%= form_with(model: booking) do |form| %>
  <% if booking.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(booking.errors.count, "error") %> prohibited this booking from being saved:</h2>

      <ul>
        <% booking.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :flight_id, style: "display: block" %>
    <%= form.text_field :flight_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/bookings/edit.html.erb
<h1>Editing booking</h1>

<%= render "form", booking: @booking %>

<br>

<div>
  <%= link_to "Show this booking", @booking %> |
  <%= link_to "Back to bookings", bookings_path %>
</div>

app/views/bookings/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Bookings</h1>

<div id="bookings">
  <% @bookings.each do |booking| %>
    <%= render booking %>
    <p>
      <%= link_to "Show this booking", booking %>
    </p>
  <% end %>
</div>

<%= link_to "New booking", new_booking_path %>

app/views/bookings/new.html.erb
<h1>New booking</h1>
  <section>
  <h2>Itinerary</h2> 
    <p>
      <%= "Flight ##{@selected_flight.id}, departing from #{@selected_flight.departure_airport.code} and 
        flying to #{@selected_flight.arrival_airport.code}
        on #{@selected_flight.start_date} at #{@selected_flight.start_time.strftime("%I:%M%p")}" %>
    </p> 
    <p>
      <%# <%= "Passenger count: #{@passengers_count}" %>
    </p>
  </section>  

<%= form_with model: @booking do |f| %>
  <%= f.hidden_field :flight_id, value: params[:flight_id] %>
  
  <%# Using a tag helper to use an instance variable (@passengers_count) to create an HTML attribute 
  which helps our JS create the correct # of passenger fields inside this div %>
  <%= tag.div data: { controller: "passenger", 
    passenger_passnum_value: @passengers_count,
    passenger_target: "passDiv",
    passenger_concealed_class: "concealed"
    }, class: "booking-form" do %>
    
    <h2>Passenger info</h2> 
    <button data-action="click->passenger#addPass">Add passenger!</button>
    <button 
      class="removeButton"
      data-action="click->passenger#removePass" 
      data-passenger-target="removeButton"
      >Remove passenger!
    </button>
    <hr>
    
    <%# fields to enter info for each passenger %> 
    <template data-passenger-target="passengerForm" >
      <%# instantiating (not saving) already-associated-objects (X passengers with the booking) %>
      <%= f.fields_for :passengers, @booking.passengers.build, child_index: 'PASSENGER_RECORD' do |passengers_attributes| %>
        <div id="newpass">
          <%= passengers_attributes.label :name %>
          <%= passengers_attributes.text_field :name, placeholder: "Passenger's name", required: true %>
          <%= passengers_attributes.label :email %>
          <%= passengers_attributes.email_field :email, placeholder: "name@example.com", required: true %>
        </div> 
      <% end %>
    </template>
     
  <% end %>

  <%= f.submit 'Purchase Ticket' %>

<% end %>

app/views/bookings/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @booking %>

<div>
  <%= link_to "Edit this booking", edit_booking_path(@booking) %> |
  <%= link_to "Back to bookings", bookings_path %>

  <%= button_to "Destroy this booking", @booking, method: :delete %>
</div>

app/views/flights/_selection_form.html.erb
  <% if @searched_flights.present? %>
    <%# Testing to see if I can get the search to work: %>
    <p><%#= @searched_flights_testb.inspect %></p>

    <%= form_with(model: @flight, url: new_booking_path, method: "get") do |form| %>
      <%= form.hidden_field :num_of_passengers, value: @num_of_passengers %>
        <h5>
          <%= "#{pluralize(@searched_flights.count, "flight")} from #{@searched_flights.first.departure_airport.code} to #{@searched_flights.first.arrival_airport.code} available!" %>
        </h5>

        <% @searched_flights.each do |flight| %>
          <div>
              <%= form.radio_button :flight_id, flight.id%>
                <%= "Flight ##{flight.id} -
                  #{flight.start_date} at #{flight.start_time.strftime("%I:%M%p")}" %>
          </div>
        <% end %>
        <%= form.submit "Book" %>
    <% end %>
  <% else %>
    <div>
      <h4>No flights found, please try again!</h4>
    </div>
  <% end %>

app/views/flights/index.html.erb
<h1>Odin Flights!</h1>

<%= form_with(url: '/flights', method: "get") do |form| %>

  <div class="dropdowns">

    <div class="flights">  
      <%= form.label :departure_id, "Departing flight:" %>
      <%= form.collection_select :departure_id, @airports, :id, :code %>
    </div>  

    <div class="flights">
      <%= form.label :arrival_id, "Arrival flight:" %>
      <%= form.collection_select :arrival_id, @airports, :id, :code %>
    </div>

    <div class="flights">
      <%= form.label :passengers_num, "# of passengers (1-4):" %>
      <%= form.select :passengers_num, ["1", "2", "3", "4"] %>
    </div>

    <div class="flights">
      <%= form.label :start_date, "Upcoming days:" %>
      <%= form.select :start_date, Date.today..Date.today + 5 %>
    </div>

    <div>
      <%= form.submit 'Search'%>
    </div>

  </div>
 
<% end %>

<%# search results will need to be in their own form with radio buttons %>
<h2>Search Results</h2>
<div class="search-results">
  <%= render "selection_form" %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OdinFlightBooker</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>